server:
  port: 8080
spring:
  profiles:
    active: @profileActive@
  application:
    name: Card-service
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

access_token: ${ACCESS_TOKEN}
refresh_token: ${REFRESH_TOKEN}