server:
  port: 8080

spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://card-service-db:5432/${DB_NAME}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

