server:
  port: 8080

spring:
  profiles:
    active: @profileActive@
  application:
    name: Card-service
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${POSTGRES_IP}:5432/${DB_NAME}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

